package stock.dao;

import stock.model.MyAction;

public interface MyActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_action
     *
     * @mbggenerated
     */
    int insert(MyAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_action
     *
     * @mbggenerated
     */
    int insertSelective(MyAction record);
}