package stock.dao;

import stock.model.MyStock;

public interface MyStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    int insert(MyStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    int insertSelective(MyStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    MyStock selectByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyStock record);
}