package stock.dao;

import stock.model.RuleRunHistory;

public interface RuleRunHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_run_history
     *
     * @mbggenerated
     */
    int insert(RuleRunHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_run_history
     *
     * @mbggenerated
     */
    int insertSelective(RuleRunHistory record);
}