package stock.dao;

import stock.model.RuleItem;

public interface RuleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_item
     *
     * @mbggenerated
     */
    int insert(RuleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_item
     *
     * @mbggenerated
     */
    int insertSelective(RuleItem record);
}