package stock.dao;

import stock.model.RuleType;

public interface RuleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_type
     *
     * @mbggenerated
     */
    int insert(RuleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_type
     *
     * @mbggenerated
     */
    int insertSelective(RuleType record);
}