package stock.dao;

import stock.model.RuleResult;

public interface RuleResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_result
     *
     * @mbggenerated
     */
    int insert(RuleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_result
     *
     * @mbggenerated
     */
    int insertSelective(RuleResult record);
}