package stock.dao;

import stock.model.Stock;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_stock
     *
     * @mbggenerated
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_stock
     *
     * @mbggenerated
     */
    int insertSelective(Stock record);
}