package stock.model;

import java.util.Date;

public class Calendar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.date
     *
     * @return the value of calendar.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.date
     *
     * @param date the value for calendar.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.is_valid
     *
     * @return the value of calendar.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.is_valid
     *
     * @param isValid the value for calendar.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}