package stock.model;

public class RuleItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_item.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_item.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_item.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_item.IMPL_CLASS
     *
     * @mbggenerated
     */
    private String implClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_item.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_item.ID
     *
     * @return the value of rule_item.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_item.ID
     *
     * @param id the value for rule_item.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_item.NAME
     *
     * @return the value of rule_item.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_item.NAME
     *
     * @param name the value for rule_item.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_item.TYPE
     *
     * @return the value of rule_item.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_item.TYPE
     *
     * @param type the value for rule_item.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_item.IMPL_CLASS
     *
     * @return the value of rule_item.IMPL_CLASS
     *
     * @mbggenerated
     */
    public String getImplClass() {
        return implClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_item.IMPL_CLASS
     *
     * @param implClass the value for rule_item.IMPL_CLASS
     *
     * @mbggenerated
     */
    public void setImplClass(String implClass) {
        this.implClass = implClass == null ? null : implClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_item.DESCRIPTION
     *
     * @return the value of rule_item.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_item.DESCRIPTION
     *
     * @param description the value for rule_item.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}