package stock.model;

import java.util.Date;

public class MyAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.TRANSACTION_ID
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.ACTION_ID
     *
     * @mbggenerated
     */
    private String actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.QUANTITY
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.PRIZE
     *
     * @mbggenerated
     */
    private Double prize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_action.ACTION_TYPE
     *
     * @mbggenerated
     */
    private Integer actionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.TRANSACTION_ID
     *
     * @return the value of my_action.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.TRANSACTION_ID
     *
     * @param transactionId the value for my_action.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.ACTION_ID
     *
     * @return the value of my_action.ACTION_ID
     *
     * @mbggenerated
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.ACTION_ID
     *
     * @param actionId the value for my_action.ACTION_ID
     *
     * @mbggenerated
     */
    public void setActionId(String actionId) {
        this.actionId = actionId == null ? null : actionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.QUANTITY
     *
     * @return the value of my_action.QUANTITY
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.QUANTITY
     *
     * @param quantity the value for my_action.QUANTITY
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.PRIZE
     *
     * @return the value of my_action.PRIZE
     *
     * @mbggenerated
     */
    public Double getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.PRIZE
     *
     * @param prize the value for my_action.PRIZE
     *
     * @mbggenerated
     */
    public void setPrize(Double prize) {
        this.prize = prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.TIME
     *
     * @return the value of my_action.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.TIME
     *
     * @param time the value for my_action.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_action.ACTION_TYPE
     *
     * @return the value of my_action.ACTION_TYPE
     *
     * @mbggenerated
     */
    public Integer getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_action.ACTION_TYPE
     *
     * @param actionType the value for my_action.ACTION_TYPE
     *
     * @mbggenerated
     */
    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }
}