package stock.model;

import java.util.Date;

public class MyStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.TRANSACTION_ID
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.STOCK_CODE
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.BUY_PRICE
     *
     * @mbggenerated
     */
    private Double buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.QUANTITY
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.OPEN_TIME
     *
     * @mbggenerated
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.IS_MONITOR
     *
     * @mbggenerated
     */
    private Integer isMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.PROFIT
     *
     * @mbggenerated
     */
    private Double profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.PROFIT_RATE
     *
     * @mbggenerated
     */
    private Double profitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_stock.CLOSE_TIME
     *
     * @mbggenerated
     */
    private Date closeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.TRANSACTION_ID
     *
     * @return the value of my_stock.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.TRANSACTION_ID
     *
     * @param transactionId the value for my_stock.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.STOCK_CODE
     *
     * @return the value of my_stock.STOCK_CODE
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.STOCK_CODE
     *
     * @param stockCode the value for my_stock.STOCK_CODE
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.BUY_PRICE
     *
     * @return the value of my_stock.BUY_PRICE
     *
     * @mbggenerated
     */
    public Double getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.BUY_PRICE
     *
     * @param buyPrice the value for my_stock.BUY_PRICE
     *
     * @mbggenerated
     */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.QUANTITY
     *
     * @return the value of my_stock.QUANTITY
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.QUANTITY
     *
     * @param quantity the value for my_stock.QUANTITY
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.OPEN_TIME
     *
     * @return the value of my_stock.OPEN_TIME
     *
     * @mbggenerated
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.OPEN_TIME
     *
     * @param openTime the value for my_stock.OPEN_TIME
     *
     * @mbggenerated
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.STATUS
     *
     * @return the value of my_stock.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.STATUS
     *
     * @param status the value for my_stock.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.IS_MONITOR
     *
     * @return the value of my_stock.IS_MONITOR
     *
     * @mbggenerated
     */
    public Integer getIsMonitor() {
        return isMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.IS_MONITOR
     *
     * @param isMonitor the value for my_stock.IS_MONITOR
     *
     * @mbggenerated
     */
    public void setIsMonitor(Integer isMonitor) {
        this.isMonitor = isMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.PROFIT
     *
     * @return the value of my_stock.PROFIT
     *
     * @mbggenerated
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.PROFIT
     *
     * @param profit the value for my_stock.PROFIT
     *
     * @mbggenerated
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.PROFIT_RATE
     *
     * @return the value of my_stock.PROFIT_RATE
     *
     * @mbggenerated
     */
    public Double getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.PROFIT_RATE
     *
     * @param profitRate the value for my_stock.PROFIT_RATE
     *
     * @mbggenerated
     */
    public void setProfitRate(Double profitRate) {
        this.profitRate = profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_stock.CLOSE_TIME
     *
     * @return the value of my_stock.CLOSE_TIME
     *
     * @mbggenerated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_stock.CLOSE_TIME
     *
     * @param closeTime the value for my_stock.CLOSE_TIME
     *
     * @mbggenerated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }
}